<?php

/**
 * Class PaanekClass
 * 范围解析操作符 （::）的使用
 * ----------调用父类的方法
 */
class PaanekClass {
    protected function myFunc(){
        echo "PaanetClass::myFunc" .PHP_EOL;
    }
}

class SunPaanekClass extends PaanekClass{
    public function myFunc()
    {
        //调用父类方法
        parent::myFunc(); // TODO: Change the autogenerated stub
        echo "SunPaanekClass::myFunc" .PHP_EOL;
    }
}

function main(){
    $obj = new SunPaanekClass();
    $obj->myFunc();
}

main();